{% set name = "flake8-typing-imports" %}
{% set version = "1.17.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/asottile/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: ea5467dbc9d334c84de764210c39b3db1adb1e895e748995ab51224a5c73a162

build:
  number: 0
  skip: true  # [py2k]
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - setuptools
    - python
  run:
    - flake8 >=3.7
    - importlib-metadata >=0.9  # [py<38]
    - python

test:
  imports:
    - flake8_typing_imports
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/flake8-typing-imports/
  summary: flake8 plugin which checks that typing imports are properly guarded
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - marcelotrevisani
