{% set name = "flake8-typing-imports" %}
{% set version = "1.12.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/asottile/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: fbf8f828215ce39d278d41e3225da945a0a3c4e0160d34f345b8e1ef8669200a

build:
  number: 1
  skip: true  # [py2k]
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python
  run:
    - flake8 >=3.7
    - importlib-metadata >=0.9  # [py<38]
    - python

test:
  imports:
    - flake8_typing_imports
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/flake8-typing-imports/
  summary: flake8 plugin which checks that typing imports are properly guarded
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - marcelotrevisani
