{% set name = "flake8-typing-imports" %}
{% set version = "1.15.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/asottile/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: f19ddb1a7ca50431edaef205af4e8dae451a69cacf070cc51b9fadd4d7857e1a

build:
  number: 1
  skip: true  # [py2k]
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python
  run:
    - flake8 >=3.7
    - importlib-metadata >=0.9  # [py<38]
    - python

test:
  imports:
    - flake8_typing_imports
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/flake8-typing-imports/
  summary: flake8 plugin which checks that typing imports are properly guarded
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - marcelotrevisani
